### ISSUE TITLE
Crate is incompatible with custon Results

### ISSUE THREAD

**Issue by Yuri6037** [ihrwein/enum-display-derive#8]
In code that uses custom Result types this crate creates a conflict and cannot be used: instead of returning a Result this crate should consider returning a "std::result::Result".

Example: in user code we might see use std::io::Result which will break this crate.

**Comment by ihrwein** [comment]
@Yuri6037 Thanks for raising this issue. Could you try https://crates.io/crates/enum-display-derive/0.1.1 and let me know whether it fixes your issue?

**Comment by Yuri6037** [comment]
I can confirm that version 0.1.1 fixes the problem.

**Comment by ihrwein** [comment]
Great, thank you.
